# Generated by Django 5.0.10 on 2025-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("advanced", "Advanced Perm"),
                    ("pro", "Pro Perm"),
                    ("basic", "Basic Perm"),
                    ("basic_ai", "Basic AI Perm"),
                ]
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="group",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
