# Generated by Django 5.0.10 on 2025-01-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_subscription_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="group",
            new_name="groups",
        ),
    ]
