# Generated by Django 5.0.10 on 2025-01-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
